# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ne.runtime.v1 import runtime_pb2 as ne_dot_runtime_dot_v1_dot_runtime__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ne/runtime/v1/runtime_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub:
    """The runtime API SDKs and (eventually) the control plane talk to.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/ne.runtime.v1.Runtime/Ping',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PingRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetRuntimeCapabilities = channel.unary_unary(
                '/ne.runtime.v1.Runtime/GetRuntimeCapabilities',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetRuntimeCapabilitiesRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetRuntimeCapabilitiesResponse.FromString,
                _registered_method=True)
        self.CreateWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/CreateWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.CreateWorkspaceResponse.FromString,
                _registered_method=True)
        self.DestroyWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/DestroyWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.DestroyWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.DestroyWorkspaceResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/ne.runtime.v1.Runtime/ExecuteCommand',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.ListEvents = channel.unary_unary(
                '/ne.runtime.v1.Runtime/ListEvents',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ListEventsRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ListEventsResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/ne.runtime.v1.Runtime/WriteFile',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/ne.runtime.v1.Runtime/ReadFile',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.PauseWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/PauseWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PauseWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PauseWorkspaceResponse.FromString,
                _registered_method=True)
        self.ResumeWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/ResumeWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ResumeWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ResumeWorkspaceResponse.FromString,
                _registered_method=True)
        self.SnapshotWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/SnapshotWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.SnapshotWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.SnapshotWorkspaceResponse.FromString,
                _registered_method=True)
        self.RestoreWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/RestoreWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.RestoreWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.RestoreWorkspaceResponse.FromString,
                _registered_method=True)
        self.ForkWorkspace = channel.unary_unary(
                '/ne.runtime.v1.Runtime/ForkWorkspace',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ForkWorkspaceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ForkWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetPoolStatus = channel.unary_unary(
                '/ne.runtime.v1.Runtime/GetPoolStatus',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetPoolStatusRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetPoolStatusResponse.FromString,
                _registered_method=True)
        self.ExposePort = channel.unary_unary(
                '/ne.runtime.v1.Runtime/ExposePort',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExposePortRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExposePortResponse.FromString,
                _registered_method=True)
        self.UnexposePort = channel.unary_unary(
                '/ne.runtime.v1.Runtime/UnexposePort',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.UnexposePortRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.UnexposePortResponse.FromString,
                _registered_method=True)
        self.GetAttestationEvidence = channel.unary_unary(
                '/ne.runtime.v1.Runtime/GetAttestationEvidence',
                request_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetAttestationEvidenceRequest.SerializeToString,
                response_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetAttestationEvidenceResponse.FromString,
                _registered_method=True)


class RuntimeServicer:
    """The runtime API SDKs and (eventually) the control plane talk to.
    """

    def Ping(self, request, context):
        """Liveness + version probe. Returns versions of both the API
        daemon and the upstream supervisor it relays to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRuntimeCapabilities(self, request, context):
        """Return the runtime's resolved execution, attestation, operation,
        capacity, and public evidence-schema capabilities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkspace(self, request, context):
        """Launch one workspace using the runtime's selected execution profile.
        The standard profile consumes the Firecracker fields below;
        confidential-azure accepts the workspace id with zeroed runtime fields.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyWorkspace(self, request, context):
        """Tear down a registered workspace and reclaim host resources.
        Maps onto SupervisorRequest::Terminate on the privileged side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Run one command inside a workspace. The API daemon relays the
        call through the supervisor, which opens a vsock connection to
        the guest agent, asks it to spawn the command, and returns the
        captured output. This operation is unary; a later API version can add
        server-streaming stdout and stderr chunks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvents(self, request, context):
        """Read entries from the supervisor's signed audit event log
        (per-event Ed25519 + Merkle chain). These events
        are what the control plane eventually aggregates into its
        tamper-evident store for compliance evidence packaging.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseWorkspace(self, request, context):
        """Pause a running workspace (freeze vCPUs in place).
        DEFERRED: unsupported on current Firecracker (vsock dies on in-place resume); use snapshot/restore. Server returns Unsupported.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeWorkspace(self, request, context):
        """Resume a previously paused workspace.
        DEFERRED: unsupported on current Firecracker (vsock dies on in-place resume); use snapshot/restore. Server returns Unsupported.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SnapshotWorkspace(self, request, context):
        """Snapshot a paused workspace into a reusable artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreWorkspace(self, request, context):
        """Restore a fresh workspace from an existing snapshot artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkWorkspace(self, request, context):
        """Fork a fresh workspace from a snapshot artifact, resetting the new
        guest's identity (hostname / machine-id / RNG) so it is distinct from
        the source and any sibling fork.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoolStatus(self, request, context):
        """Query warm-pool status for the configured tier (if any).
        Returns immediately from the pool manager's in-memory state; safe
        to call at high frequency for dashboard/health probes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExposePort(self, request, context):
        """Expose a guest port to host-based ingress routing, reachable at
        {port}-{workspace_id}.{ingress_domain}. Optional per-port header
        injection. The workspace must be networked.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnexposePort(self, request, context):
        """Stop routing ingress to a previously exposed guest port.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttestationEvidence(self, request, context):
        """Generate attestation evidence for a workspace, binding a caller
        nonce (challenge-response). The active provider determines the
        proof type; the software fallback is Ed25519-signed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PingRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PingResponse.SerializeToString,
            ),
            'GetRuntimeCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRuntimeCapabilities,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetRuntimeCapabilitiesRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetRuntimeCapabilitiesResponse.SerializeToString,
            ),
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'DestroyWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.DestroyWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.DestroyWorkspaceResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'ListEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvents,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ListEventsRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ListEventsResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.WriteFileRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.WriteFileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ReadFileRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ReadFileResponse.SerializeToString,
            ),
            'PauseWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PauseWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.PauseWorkspaceResponse.SerializeToString,
            ),
            'ResumeWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ResumeWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ResumeWorkspaceResponse.SerializeToString,
            ),
            'SnapshotWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.SnapshotWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.SnapshotWorkspaceResponse.SerializeToString,
            ),
            'RestoreWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.RestoreWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.RestoreWorkspaceResponse.SerializeToString,
            ),
            'ForkWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkWorkspace,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ForkWorkspaceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ForkWorkspaceResponse.SerializeToString,
            ),
            'GetPoolStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoolStatus,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetPoolStatusRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetPoolStatusResponse.SerializeToString,
            ),
            'ExposePort': grpc.unary_unary_rpc_method_handler(
                    servicer.ExposePort,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExposePortRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.ExposePortResponse.SerializeToString,
            ),
            'UnexposePort': grpc.unary_unary_rpc_method_handler(
                    servicer.UnexposePort,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.UnexposePortRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.UnexposePortResponse.SerializeToString,
            ),
            'GetAttestationEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttestationEvidence,
                    request_deserializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetAttestationEvidenceRequest.FromString,
                    response_serializer=ne_dot_runtime_dot_v1_dot_runtime__pb2.GetAttestationEvidenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ne.runtime.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ne.runtime.v1.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime:
    """The runtime API SDKs and (eventually) the control plane talk to.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/Ping',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.PingRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRuntimeCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/GetRuntimeCapabilities',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.GetRuntimeCapabilitiesRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.GetRuntimeCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/CreateWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.CreateWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.CreateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/DestroyWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.DestroyWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.DestroyWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/ExecuteCommand',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteCommandRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/ListEvents',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ListEventsRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ListEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/WriteFile',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.WriteFileRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/ReadFile',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ReadFileRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/PauseWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.PauseWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.PauseWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/ResumeWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ResumeWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ResumeWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SnapshotWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/SnapshotWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.SnapshotWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.SnapshotWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/RestoreWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.RestoreWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.RestoreWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/ForkWorkspace',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ForkWorkspaceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ForkWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoolStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/GetPoolStatus',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.GetPoolStatusRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.GetPoolStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExposePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/ExposePort',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ExposePortRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.ExposePortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnexposePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/UnexposePort',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.UnexposePortRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.UnexposePortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttestationEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ne.runtime.v1.Runtime/GetAttestationEvidence',
            ne_dot_runtime_dot_v1_dot_runtime__pb2.GetAttestationEvidenceRequest.SerializeToString,
            ne_dot_runtime_dot_v1_dot_runtime__pb2.GetAttestationEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
